version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: service_station
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
      - "5452:5432"
    