\copy public.brand(brand_id, name) FROM '/home/ira/Desktop/uni/kw/service_station_data\brand.csv' WITH (FORMAT csv, HEADER true);
\copy public.characteristic(characteristic_id, name) FROM '/home/ira/Desktop/uni/kw/service_station_data\characteristic.csv' WITH (FORMAT csv, HEADER true);
\copy public.client(client_id, first_name, last_name, phone_number) FROM '/home/ira/Desktop/uni/kw/service_station_data\client.csv' WITH (FORMAT csv, HEADER true);
\copy public.country(country_id, name) FROM '/home/ira/Desktop/uni/kw/service_station_data\country.csv' WITH (FORMAT csv, HEADER true);
\copy public.detail_group(detail_group_id, name) FROM '/home/ira/Desktop/uni/kw/service_station_data\detail_group.csv' WITH (FORMAT csv, HEADER true);
\copy public.employee_role(role_id, name) FROM '/home/ira/Desktop/uni/kw/service_station_data\employee_role.csv' WITH (FORMAT csv, HEADER true);
\copy public.payment_status(status_id, title) FROM '/home/ira/Desktop/uni/kw/service_station_data\payment_status.csv' WITH (FORMAT csv, HEADER true);
\copy public.repair_status(status_id, title) FROM '/home/ira/Desktop/uni/kw/service_station_data\repair_status.csv' WITH (FORMAT csv, HEADER true);
\copy public.service(service_id, name, description, price, estimated_duration) FROM '/home/ira/Desktop/uni/kw/service_station_data\service.csv' WITH (FORMAT csv, HEADER true);
\copy public.supply_status(status_id, title) FROM '/home/ira/Desktop/uni/kw/service_station_data\supply_status.csv' WITH (FORMAT csv, HEADER true);
\copy public.car(car_id, year, body_type, model, brand_id) FROM '/home/ira/Desktop/uni/kw/service_station_data\car.csv' WITH (FORMAT csv, HEADER true);
\copy public.car_client(car_client_id, car_id, client_id, description, registration_number, vin, color) FROM '/home/ira/Desktop/uni/kw/service_station_data\car_client.csv' WITH (FORMAT csv, HEADER true);
\copy public.city(city_id, name, country_id) FROM '/home/ira/Desktop/uni/kw/service_station_data\city.csv' WITH (FORMAT csv, HEADER true);
\copy public.detail_type(detail_type_id, name, detail_group_id) FROM '/home/ira/Desktop/uni/kw/service_station_data\detail_type.csv' WITH (FORMAT csv, HEADER true);
\copy public.manufacturer(manufacturer_id, country_id, name) FROM '/home/ira/Desktop/uni/kw/service_station_data\manufacturer.csv' WITH (FORMAT csv, HEADER true);
\copy public.service_station(station_id, address, city_id) FROM '/home/ira/Desktop/uni/kw/service_station_data\service_station.csv' WITH (FORMAT csv, HEADER true);
\copy public.supplier(supplier_id, name, city_id, phone_number, address) FROM '/home/ira/Desktop/uni/kw/service_station_data\supplier.csv' WITH (FORMAT csv, HEADER true);
\copy public.detail(detail_id, description, manufacturer_id, detail_type_id, article, price, dimensions, weight) FROM '/home/ira/Desktop/uni/kw/service_station_data\detail.csv' WITH (FORMAT csv, HEADER true);
\copy public.detail_characteristic(characteristic_id, detail_id, value) FROM '/home/ira/Desktop/uni/kw/service_station_data\detail_characteristic.csv' WITH (FORMAT csv, HEADER true);
\copy public.employee(employee_id, first_name, last_name, phone_number, role_id, service_station_id) FROM '/home/ira/Desktop/uni/kw/service_station_data\employee.csv' WITH (FORMAT csv, HEADER true);
\copy public.inventory(inventory_id, detail_id, quantity, service_station_id) FROM '/home/ira/Desktop/uni/kw/service_station_data\inventory.csv' WITH (FORMAT csv, HEADER true);
\copy public.repair_order(repair_id, employee_id, start_date, repair_status_id, notes, repair_number, payment_status_id, car_client_id, total_sum) FROM '/home/ira/Desktop/uni/kw/service_station_data\repair_order.csv' WITH (FORMAT csv, HEADER true);
\copy public.service_repairs(service_repairs_id, service_id, repair_id, quantity, completion_date, service_total_price) FROM '/home/ira/Desktop/uni/kw/service_station_data\service_repairs.csv' WITH (FORMAT csv, HEADER true);
\copy public.supply(supply_id, supply_number, total_sum, supply_date, status_id, supplier_id, employee_id) FROM '/home/ira/Desktop/uni/kw/service_station_data\supply.csv' WITH (FORMAT csv, HEADER true);
\copy public.supply_details(supply_details_id, detail_id, quantity, price_per_unit, supply_id) FROM '/home/ira/Desktop/uni/kw/service_station_data\supply_details.csv' WITH (FORMAT csv, HEADER true);
\copy public.supply_invoice(supply_invoice_id, supply_details_id, invoice_number, inventory_id) FROM '/home/ira/Desktop/uni/kw/service_station_data\supply_invoice.csv' WITH (FORMAT csv, HEADER true);
\copy public.service_inventory(service_inventory_id, service_repair_id, inventory_id, amount) FROM '/home/ira/Desktop/uni/kw/service_station_data\service_inventory.csv' WITH (FORMAT csv, HEADER true);
