ALTER TABLE country 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE supply_status 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE brand 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE car 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE detail_group 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE characteristic 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE employee_role 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE payment_status 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE repair_status 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE service 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE car_client 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE client 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE city 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE detail_type 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE manufacturer 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE service_station 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE supplier 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE detail 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE detail_characteristic 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE service_repairs 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE employee 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE inventory 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE repair_order 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE supply 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE supply_details 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE supply_invoice 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE service_inventory 
       ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
       ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;



       CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    RAISE NOTICE 'Trigger called for table % on column % at time %', TG_TABLE_NAME, 'updated_at', CURRENT_TIMESTAMP;
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;




DO $$
DECLARE
    row record;
BEGIN
    FOR row IN SELECT table_name FROM information_schema.tables
               WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
    LOOP
        -- Перевірка чи існує колонка `updated_at`
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_schema = 'public' AND table_name = row.table_name AND column_name = 'updated_at') THEN
            EXECUTE format('CREATE TRIGGER update_%1$I_updated_at BEFORE UPDATE ON public.%1$I 
                            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()', row.table_name);
        END IF;
    END LOOP;
END;
$$;
