// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbs

import (
	"database/sql"
	"time"
)

type Brand struct {
	BrandID   int32
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Car struct {
	CarID     int32
	Year      sql.NullInt32
	BodyType  sql.NullString
	Model     sql.NullString
	BrandID   sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type CarClient struct {
	CarClientID        int32
	CarID              int32
	ClientID           int32
	Description        sql.NullString
	RegistrationNumber sql.NullString
	Vin                sql.NullString
	Color              sql.NullString
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type Characteristic struct {
	CharacteristicID int32
	Name             string
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type City struct {
	CityID    int32
	Name      string
	CountryID sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Client struct {
	ClientID    int32
	FirstName   string
	LastName    string
	PhoneNumber sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Country struct {
	CountryID int32
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Detail struct {
	DetailID       int32
	Description    string
	ManufacturerID sql.NullInt32
	DetailTypeID   sql.NullInt32
	Article        sql.NullInt32
	Price          sql.NullString
	Dimensions     sql.NullString
	Weight         sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type DetailCharacteristic struct {
	CharacteristicID int32
	DetailID         int32
	Value            sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type DetailGroup struct {
	DetailGroupID int32
	Name          string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type DetailType struct {
	DetailTypeID  int32
	Name          string
	DetailGroupID sql.NullInt32
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Employee struct {
	EmployeeID       int32
	FirstName        string
	LastName         string
	PhoneNumber      sql.NullString
	RoleID           sql.NullInt32
	ServiceStationID sql.NullInt32
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type EmployeeRole struct {
	RoleID    int32
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Inventory struct {
	InventoryID      int32
	DetailID         sql.NullInt32
	Quantity         sql.NullInt32
	ServiceStationID sql.NullInt32
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type Manufacturer struct {
	ManufacturerID int32
	CountryID      sql.NullInt32
	Name           string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type MetaDataloadhistory struct {
	DataLoadHistoryID  int32
	LoadDatetime       sql.NullTime
	LoadTime           sql.NullTime
	LoadRows           sql.NullInt32
	AffectedTableCount sql.NullInt32
	SourceTableCount   sql.NullInt32
}

type MetaDimension struct {
	DimensionID   int32
	DwTableID     sql.NullInt32
	KeyName       sql.NullString
	DimensionType sql.NullString
	DimensionName sql.NullString
}

type MetaDimensionattribute struct {
	DimensionID         sql.NullInt32
	DwAttributeColumnID sql.NullInt32
}

type MetaDwattributecolumn struct {
	DwAttributeColumnID       int32
	DwAttributeColumnName     sql.NullString
	DwAttributeColumnDatatype sql.NullString
}

type MetaDwtable struct {
	DwTableID         int32
	DataLoadHistoryID sql.NullInt32
	DwTableName       sql.NullString
}

type MetaFact struct {
	FactID    int32
	KeyName   sql.NullString
	DwTableID sql.NullInt32
	FactType  sql.NullString
}

type MetaFactmetric struct {
	FactMetricID          int32
	FactID                sql.NullInt32
	DwAttributeColumnID   sql.NullInt32
	FactMetricDescription sql.NullString
}

type MetaSourcecolumn struct {
	SourceColumnID   int32
	SourceTableID    sql.NullInt32
	SourceColumnName sql.NullString
	DataType         sql.NullString
}

type MetaSourcedb struct {
	SourceDbID   int32
	SourceDbName sql.NullString
}

type MetaSourcetable struct {
	SourceTableID   int32
	SourceDbID      sql.NullInt32
	KeyName         sql.NullString
	SourceTableName sql.NullString
}

type MetaTransformation struct {
	TransformationID    int32
	DwAttributeColumnID sql.NullInt32
	TransformationRule  sql.NullString
	SourceColumnID      sql.NullInt32
}

type PaymentStatus struct {
	StatusID  int32
	Title     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type RepairOrder struct {
	RepairID        int32
	EmployeeID      sql.NullInt32
	StartDate       sql.NullTime
	RepairStatusID  sql.NullInt32
	Notes           sql.NullString
	RepairNumber    sql.NullString
	PaymentStatusID sql.NullInt32
	CarClientID     sql.NullInt32
	TotalSum        sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type RepairStatus struct {
	StatusID  int32
	Title     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Service struct {
	ServiceID         int32
	Name              string
	Description       sql.NullString
	Price             sql.NullString
	EstimatedDuration sql.NullString
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type ServiceInventory struct {
	ServiceInventoryID int32
	ServiceRepairID    sql.NullInt32
	InventoryID        sql.NullInt32
	Amount             sql.NullString
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type ServiceRepair struct {
	ServiceRepairsID  int32
	ServiceID         sql.NullInt32
	RepairID          sql.NullInt32
	Quantity          sql.NullInt32
	CompletionDate    sql.NullTime
	ServiceTotalPrice sql.NullString
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type ServiceStation struct {
	StationID int32
	Address   string
	CityID    sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type StageDetail struct {
	DetailID       int32
	Description    sql.NullString
	ManufacturerID sql.NullInt32
	DetailTypeID   sql.NullInt32
	Article        sql.NullString
	Price          sql.NullString
	Dimensions     sql.NullString
	Weight         sql.NullString
}

type StageInventory struct {
	InventoryID      int32
	DetailID         sql.NullInt32
	Quantity         sql.NullInt32
	ServiceStationID sql.NullInt32
}

type StageRepair struct {
	RepairID        int32
	EmployeeID      sql.NullInt32
	StartDate       sql.NullTime
	RepairStatusID  sql.NullInt32
	Notes           sql.NullString
	RepairNumber    sql.NullString
	PaymentStatusID sql.NullInt32
	CarClientID     sql.NullInt32
	TotalSum        sql.NullString
}

type StageService struct {
	ServiceID         int32
	Name              sql.NullString
	Description       sql.NullString
	Price             sql.NullString
	EstimatedDuration sql.NullInt64
}

type StageServiceInventory struct {
	ServiceInventoryID int32
	ServiceRepairID    sql.NullInt32
	InventoryID        sql.NullInt32
	Amount             sql.NullInt32
}

type StageServiceRepair struct {
	ServiceRepairsID  int32
	ServiceID         sql.NullInt32
	RepairID          sql.NullInt32
	Quantity          sql.NullInt32
	CompletionDate    sql.NullTime
	ServiceTotalPrice sql.NullString
}

type StageSupplier struct {
	SupplierID  int32
	Name        sql.NullString
	CityID      sql.NullInt32
	PhoneNumber sql.NullString
	Address     sql.NullString
}

type StageSupply struct {
	SupplyID     int32
	SupplyNumber sql.NullString
	SupplyDate   sql.NullTime
	TotalSum     sql.NullString
	StatusID     sql.NullInt32
	SupplierID   sql.NullInt32
	EmployeeID   sql.NullInt32
}

type StageSupplyDetail struct {
	SupplyDetailsID int32
	DetailID        sql.NullInt32
	Quantity        sql.NullInt32
	PricePerUnit    sql.NullString
	SupplyID        sql.NullInt32
}

type StorageDateDim struct {
	DateID int32
	Year   sql.NullInt32
	Month  sql.NullInt32
	Day    sql.NullInt32
}

type StorageInventoryDim struct {
	InventoryDimID int32
	BkDetailID     int32
	Description    sql.NullString
	Article        sql.NullString
	Price          sql.NullString
	Dimensions     sql.NullString
	Weight         sql.NullString
}

type StorageRepairDim struct {
	RepairDimID          int32
	BkRepairID           int32
	Notes                sql.NullString
	RepairNumber         sql.NullString
	StartRepairDateDimID sql.NullInt32
}

type StorageServiceDim struct {
	ServiceDimID      int32
	BkServiceID       int32
	Name              sql.NullString
	Description       sql.NullString
	Price             sql.NullString
	EstimatedDuration sql.NullString
}

type StorageServiceInventoryFact struct {
	ServiceInventoryFactID   int32
	ServiceRepairDimID       int32
	InventoryDimID           int32
	PartsCost                sql.NullString
	TotalCost                sql.NullString
	PartsCostPercentage      sql.NullString
	ActualServiceDuration    sql.NullString
	EstimatedServiceDuration sql.NullString
	ServiceDurationDeviation sql.NullString
	BkServiceInventoryID     int32
	Amount                   sql.NullString
}

type StorageServiceRepairDim struct {
	ServiceRepairDimID int32
	ServiceID          int32
	RepairID           int32
	Quantity           sql.NullInt32
	ServiceTotalPrice  sql.NullString
	CompleteDateDimID  sql.NullInt32
	BkServiceRepair    int32
}

type StorageSupplierDim struct {
	SupplierDimID int32
	BkSupplierID  int32
	Name          sql.NullString
	PhoneNumber   sql.NullString
	Address       sql.NullString
}

type StorageSupplyDetailsFact struct {
	SupplyDetailsFactID int32
	DetailDimID         int32
	DetailQuantity      sql.NullInt32
	DetailTotalCost     sql.NullString
	SupplierID          sql.NullInt32
	StartDateDimID      sql.NullInt32
	EndDateDimID        sql.NullInt32
}

type Supplier struct {
	SupplierID  int32
	Name        string
	CityID      sql.NullInt32
	PhoneNumber sql.NullString
	Address     string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Supply struct {
	SupplyID     int32
	SupplyNumber string
	TotalSum     sql.NullString
	SupplyDate   time.Time
	StatusID     sql.NullInt32
	SupplierID   sql.NullInt32
	EmployeeID   sql.NullInt32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type SupplyDetail struct {
	SupplyDetailsID int32
	DetailID        sql.NullInt32
	Quantity        sql.NullInt32
	PricePerUnit    sql.NullString
	SupplyID        sql.NullInt32
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type SupplyInvoice struct {
	SupplyInvoiceID int32
	SupplyDetailsID sql.NullInt32
	InvoiceNumber   sql.NullString
	InventoryID     int32
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type SupplyStatus struct {
	StatusID  int32
	Title     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
